from __future__ import annotations

from .raw_common import _env_path, _repo_root, _seg_dataset_root


DEFAULT_REPO_ROOT = _repo_root()
DEFAULT_SEG_DATASET_ROOT = _seg_dataset_root(DEFAULT_REPO_ROOT)

DEFAULT_AIHUB_ROOT = _env_path("PV26_AIHUB_ROOT", DEFAULT_SEG_DATASET_ROOT / "AIHUB")
DEFAULT_AIHUB_DOCS_ROOT = DEFAULT_AIHUB_ROOT / "docs"
DEFAULT_AIHUB_LANE_ROOT = DEFAULT_AIHUB_ROOT / "차선-횡단보도 인지 영상(수도권)"
DEFAULT_AIHUB_OBSTACLE_ROOT = DEFAULT_AIHUB_ROOT / "도로장애물·표면 인지 영상(수도권)"
DEFAULT_AIHUB_TRAFFIC_ROOT = DEFAULT_AIHUB_ROOT / "신호등-도로표지판 인지 영상(수도권)"
DEFAULT_AIHUB_OUTPUT_ROOT = _env_path(
    "PV26_AIHUB_OUTPUT_ROOT",
    DEFAULT_AIHUB_ROOT.parent / "pv26_aihub_standardized",
)

DEFAULT_BDD_ROOT = _env_path("PV26_BDD_ROOT", DEFAULT_SEG_DATASET_ROOT / "BDD100K")
DEFAULT_BDD_IMAGES_ROOT = DEFAULT_BDD_ROOT / "bdd100k_images_100k" / "100k"
DEFAULT_BDD_LABELS_ROOT = DEFAULT_BDD_ROOT / "bdd100k_labels" / "100k"
DEFAULT_BDD_OUTPUT_ROOT = _env_path(
    "PV26_BDD_OUTPUT_ROOT",
    DEFAULT_BDD_ROOT.parent / "pv26_bdd100k_standardized",
)

DEFAULT_DEBUG_VIS_SEED = 26

AIHUB_LANE_DIRNAME = DEFAULT_AIHUB_LANE_ROOT.name
AIHUB_OBSTACLE_DIRNAME = DEFAULT_AIHUB_OBSTACLE_ROOT.name
AIHUB_TRAFFIC_DIRNAME = DEFAULT_AIHUB_TRAFFIC_ROOT.name

BOOTSTRAP_SOURCE_KEYS = ("bdd100k_det_100k", "aihub_traffic_seoul", "aihub_obstacle_seoul")
EXCLUDED_SOURCE_KEYS = ("aihub_lane_seoul",)


__all__ = [
    "AIHUB_LANE_DIRNAME",
    "AIHUB_OBSTACLE_DIRNAME",
    "AIHUB_TRAFFIC_DIRNAME",
    "BOOTSTRAP_SOURCE_KEYS",
    "DEFAULT_AIHUB_DOCS_ROOT",
    "DEFAULT_AIHUB_LANE_ROOT",
    "DEFAULT_AIHUB_OBSTACLE_ROOT",
    "DEFAULT_AIHUB_OUTPUT_ROOT",
    "DEFAULT_AIHUB_ROOT",
    "DEFAULT_AIHUB_TRAFFIC_ROOT",
    "DEFAULT_BDD_IMAGES_ROOT",
    "DEFAULT_BDD_LABELS_ROOT",
    "DEFAULT_BDD_OUTPUT_ROOT",
    "DEFAULT_BDD_ROOT",
    "DEFAULT_DEBUG_VIS_SEED",
    "DEFAULT_REPO_ROOT",
    "DEFAULT_SEG_DATASET_ROOT",
    "EXCLUDED_SOURCE_KEYS",
]
