from __future__ import annotations

import argparse
from dataclasses import asdict, replace
import json
from pathlib import Path
import site
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
repo_root = str(REPO_ROOT)
if repo_root not in sys.path:
    site.addsitedir(repo_root)

from tools.pv26_train import cli as train_cli


STAGE4 = "stage_4_lane_family_finetune"
EXPERIMENTS = {
    "upper_trunk_rebalance": {
        "freeze_policy": "lane_family_plus_upper_trunk",
        "trunk_lr": 2.0e-6,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 1.25,
            "stop_line": 2.0,
            "crosswalk": 1.5,
        },
    },
    "heads_rebalance": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 1.25,
            "stop_line": 2.0,
            "crosswalk": 1.5,
        },
    },
    "dense_sharpen_rebalance": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 1.75,
            "stop_line": 2.25,
            "crosswalk": 1.0,
        },
        "overrides": {
            "lane_segfirst_loss_weights": {
                "centerline_bce": 1.5,
                "centerline_dice": 1.5,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_rebalance": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.25,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "hybrid_centerline_rebalance": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.0,
            "stop_line": 1.75,
            "crosswalk": 1.5,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "hybrid",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 1.75,
                "centerline_dice": 1.75,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_cross_retain": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_low_lr": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 5.0e-5,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.25,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_posw8": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.25,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_centerline_max_positive_weight": 8.0,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.25,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_cross_retain": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_stop_selector_rowx_band": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_selector_target_mode": "rowx_band",
            "stop_line_component_gate_source": "selector",
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_row_scan_vectorizer": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_row_scan_tangent_link": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_residual_local_separation": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_residual_risk_core_weight": 0.5,
            "lane_segfirst_residual_risk_ring_weight": 0.35,
            "lane_segfirst_residual_risk_ring_margin": 0.20,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_stop_retain": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.25,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_dice_focus": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.25,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 1.5,
                "centerline_dice": 3.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_upper_trunk": {
        "freeze_policy": "lane_family_plus_upper_trunk",
        "trunk_lr": 2.0e-6,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.25,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_upper_trunk_pcgrad": {
        "freeze_policy": "lane_family_plus_upper_trunk",
        "trunk_lr": 2.0e-6,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "multitask_conflict": {
                "enabled": True,
                "mode": "pcgrad_style",
                "tasks": ["lane", "stop_line", "crosswalk"],
            },
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "core_centerline_head_pcgrad": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "multitask_conflict": {
                "enabled": True,
                "mode": "pcgrad_style",
                "tasks": ["lane", "stop_line", "crosswalk"],
                "param_groups": ["heads"],
            },
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "core_centerline_shared_adapter_pcgrad": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_family_shared_adapter_enabled": True,
            "multitask_conflict": {
                "enabled": True,
                "mode": "pcgrad_style",
                "tasks": ["lane", "stop_line", "crosswalk"],
                "param_groups": ["lane_family_adapters"],
            },
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "core_centerline_task_adapter_routing": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_family_task_adapter_enabled": True,
            "multitask_conflict": {
                "enabled": False,
                "mode": "none",
                "tasks": ["lane", "stop_line", "crosswalk"],
                "param_groups": ["trunk"],
            },
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "core_centerline_refine_stop_cross_adapt": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 0.0,
            "stop_line": 2.25,
            "crosswalk": 1.50,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_balanced_retain": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.0,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_cross_focus": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 2.25,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "core_centerline_refine_cross_retain_low_lr": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 5.0e-5,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
    "stopline_haf_consensus_segment": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_haf_aux_weight": 1.0,
            "stop_line_haf_enabled": True,
            "stop_line_haf_valid_threshold": 0.85,
            "stop_line_haf_min_votes": 3,
            "stop_line_haf_cluster_endpoint_tolerance": 4.0,
            "stop_line_haf_max_endpoint_covariance": 16.0,
            "stop_line_haf_max_segments": 4,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_axis_distance_field": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_axis_distance_aux_weight": 1.0,
            "stop_line_axis_distance_enabled": True,
            "stop_line_axis_distance_valid_threshold": 0.80,
            "stop_line_axis_distance_min_votes": 3,
            "stop_line_axis_distance_cluster_endpoint_tolerance": 4.0,
            "stop_line_axis_distance_max_endpoint_covariance": 16.0,
            "stop_line_axis_distance_min_support_score": 0.35,
            "stop_line_axis_distance_max_segments": 4,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_seeded_segment_set": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_segment_set_aux_weight": 1.0,
            "stop_line_segment_set_enabled": True,
            "stop_line_segment_set_score_threshold": 0.55,
            "stop_line_segment_set_max_segments": 4,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_segment_aligned_verifier": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_segment_set_aux_weight": 1.0,
            "stopline_segment_verifier_aux_weight": 1.0,
            "stop_line_segment_set_enabled": True,
            "stop_line_segment_set_score_threshold": 0.55,
            "stop_line_segment_set_max_segments": 4,
            "stop_line_segment_verifier_score_weight": 1.0,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_segment_metric_quality_verifier": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_segment_set_aux_weight": 1.0,
            "stopline_segment_verifier_aux_weight": 1.0,
            "stopline_segment_verifier_target_mode": "metric_quality",
            "stopline_segment_verifier_quality_tau_px": 24.0,
            "stop_line_segment_set_enabled": True,
            "stop_line_segment_set_score_threshold": 0.55,
            "stop_line_segment_set_max_segments": 4,
            "stop_line_segment_verifier_score_weight": 1.0,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_segment_denoise_seeded": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_segment_set_aux_weight": 1.0,
            "stopline_segment_verifier_aux_weight": 1.0,
            "stopline_segment_denoise_aux_weight": 1.0,
            "stop_line_segment_set_enabled": True,
            "stop_line_segment_set_score_threshold": 0.55,
            "stop_line_segment_set_max_segments": 4,
            "stop_line_segment_verifier_score_weight": 1.0,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_axis_profile_segment_head": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_axis_segment_set_aux_weight": 1.0,
            "stopline_axis_segment_verifier_aux_weight": 1.0,
            "stopline_segment_verifier_target_mode": "metric_quality",
            "stopline_segment_verifier_quality_tau_px": 24.0,
            "stop_line_axis_segment_set_enabled": True,
            "stop_line_axis_segment_set_score_threshold": 0.55,
            "stop_line_axis_segment_set_max_segments": 4,
            "stop_line_axis_segment_verifier_score_weight": 1.0,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_local_patch_segment_head": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_patch_segment_set_aux_weight": 1.0,
            "stopline_patch_segment_verifier_aux_weight": 1.0,
            "stopline_segment_verifier_target_mode": "metric_quality",
            "stopline_segment_verifier_quality_tau_px": 24.0,
            "stop_line_patch_segment_set_enabled": True,
            "stop_line_patch_segment_set_score_threshold": 0.55,
            "stop_line_patch_segment_set_max_segments": 4,
            "stop_line_patch_segment_verifier_score_weight": 1.0,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_dual_endpoint_pair_head": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_endpoint_pair_aux_weight": 1.0,
            "stop_line_endpoint_pair_enabled": True,
            "stop_line_endpoint_pair_score_threshold": 0.55,
            "stop_line_endpoint_pair_topk": 12,
            "stop_line_endpoint_pair_max_segments": 4,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_endpoint_pair_metric_verifier": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stopline_endpoint_pair_aux_weight": 1.0,
            "stopline_endpoint_pair_segment_aux_weight": 1.0,
            "stopline_endpoint_pair_verifier_aux_weight": 1.0,
            "stopline_segment_verifier_target_mode": "metric_quality",
            "stopline_segment_verifier_quality_tau_px": 24.0,
            "stop_line_endpoint_pair_enabled": False,
            "stop_line_endpoint_pair_segment_enabled": True,
            "stop_line_endpoint_pair_segment_score_threshold": 0.50,
            "stop_line_endpoint_pair_segment_max_segments": 3,
            "stop_line_endpoint_pair_verifier_score_weight": 1.0,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "stopline_projection_comp_runtime": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stop_line_projection_comp_enabled": True,
            "stop_line_projection_comp_min_gap": 4.0,
            "stop_line_projection_comp_topk": 50,
            "stop_line_projection_comp_union_min_score": 0.80,
            "stop_line_projection_comp_single_min_score": 0.90,
            "stop_line_projection_comp_angle_threshold_deg": 16.0,
            "stop_line_projection_comp_offset_threshold_px": 48.0,
            "stop_line_projection_comp_min_cluster_count": 2,
            "stop_line_projection_comp_projection_gap_px": 320.0,
            "stop_line_projection_comp_max_predictions": 2,
            "stop_line_projection_comp_second_min_fragment_count": 5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "task_loss_ema_balancer": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stop_line_projection_comp_enabled": True,
            "stop_line_projection_comp_min_gap": 4.0,
            "stop_line_projection_comp_topk": 50,
            "stop_line_projection_comp_union_min_score": 0.80,
            "stop_line_projection_comp_single_min_score": 0.90,
            "stop_line_projection_comp_angle_threshold_deg": 16.0,
            "stop_line_projection_comp_offset_threshold_px": 48.0,
            "stop_line_projection_comp_min_cluster_count": 2,
            "stop_line_projection_comp_projection_gap_px": 320.0,
            "stop_line_projection_comp_max_predictions": 2,
            "stop_line_projection_comp_second_min_fragment_count": 5,
            "crosswalk_polygon_mode": "hull",
            "task_loss_normalize_mode": "ema",
            "task_loss_normalize_tasks": ["lane", "stop_line", "crosswalk"],
            "task_loss_ema_decay": 0.90,
            "task_loss_ema_warmup_steps": 8,
            "task_loss_scale_min": 0.50,
            "task_loss_scale_max": 2.00,
        },
    },
    "lane_conditional_row_instance_decoder": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_conditional_row_aux_weight": 1.0,
            "lane_conditional_row_enabled": True,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "lane_conditional_bottom_anchor_quality": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_conditional_row_aux_weight": 1.0,
            "lane_conditional_seed_target_mode": "bottom_anchor",
            "lane_conditional_objectness_target_mode": "metric_quality",
            "lane_conditional_row_x_weight": 0.5,
            "lane_conditional_row_enabled": True,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stop_line_projection_comp_enabled": True,
            "stop_line_projection_comp_min_gap": 4.0,
            "stop_line_projection_comp_topk": 50,
            "stop_line_projection_comp_union_min_score": 0.80,
            "stop_line_projection_comp_single_min_score": 0.90,
            "stop_line_projection_comp_angle_threshold_deg": 16.0,
            "stop_line_projection_comp_offset_threshold_px": 48.0,
            "stop_line_projection_comp_min_cluster_count": 2,
            "stop_line_projection_comp_projection_gap_px": 320.0,
            "stop_line_projection_comp_max_predictions": 2,
            "stop_line_projection_comp_second_min_fragment_count": 5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "lane_seed_trace_instance_decoder": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent_seed_trace",
            "lane_conditional_seed_aux_weight": 1.0,
            "lane_conditional_seed_target_mode": "bottom_anchor",
            "lane_segfirst_seed_threshold": 0.50,
            "lane_segfirst_seed_trace_max_seeds": 24,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stop_line_projection_comp_enabled": True,
            "stop_line_projection_comp_min_gap": 4.0,
            "stop_line_projection_comp_topk": 50,
            "stop_line_projection_comp_union_min_score": 0.80,
            "stop_line_projection_comp_single_min_score": 0.90,
            "stop_line_projection_comp_angle_threshold_deg": 16.0,
            "stop_line_projection_comp_offset_threshold_px": 48.0,
            "stop_line_projection_comp_min_cluster_count": 2,
            "stop_line_projection_comp_projection_gap_px": 320.0,
            "stop_line_projection_comp_max_predictions": 2,
            "stop_line_projection_comp_second_min_fragment_count": 5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "lane_seed_branch_only_trace": {
        "freeze_policy": "lane_conditional_seed_only",
        "trunk_lr": 0.0,
        "head_lr": 5.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 0.0,
            "crosswalk": 0.0,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent_seed_trace",
            "lane_conditional_seed_aux_weight": 1.0,
            "lane_conditional_seed_target_mode": "bottom_anchor",
            "lane_segfirst_seed_threshold": 0.50,
            "lane_segfirst_seed_trace_max_seeds": 24,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 0.0,
                "centerline_dice": 0.0,
                "support_bce": 0.0,
                "tangent": 0.0,
                "color": 0.0,
                "type": 0.0,
            },
            "stopline_center_target_mode": "heatmap",
            "stop_line_projection_comp_enabled": True,
            "stop_line_projection_comp_min_gap": 4.0,
            "stop_line_projection_comp_topk": 50,
            "stop_line_projection_comp_union_min_score": 0.80,
            "stop_line_projection_comp_single_min_score": 0.90,
            "stop_line_projection_comp_angle_threshold_deg": 16.0,
            "stop_line_projection_comp_offset_threshold_px": 48.0,
            "stop_line_projection_comp_min_cluster_count": 2,
            "stop_line_projection_comp_projection_gap_px": 320.0,
            "stop_line_projection_comp_max_predictions": 2,
            "stop_line_projection_comp_second_min_fragment_count": 5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "lane_bidirectional_seed_trace": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent_bidirectional_seed_trace",
            "lane_conditional_seed_aux_weight": 0.5,
            "lane_conditional_seed_target_mode": "centerline_core",
            "lane_segfirst_seed_threshold": 0.65,
            "lane_segfirst_seed_trace_max_seeds": 12,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stop_line_projection_comp_enabled": True,
            "stop_line_projection_comp_min_gap": 4.0,
            "stop_line_projection_comp_topk": 50,
            "stop_line_projection_comp_union_min_score": 0.80,
            "stop_line_projection_comp_single_min_score": 0.90,
            "stop_line_projection_comp_angle_threshold_deg": 16.0,
            "stop_line_projection_comp_offset_threshold_px": 48.0,
            "stop_line_projection_comp_min_cluster_count": 2,
            "stop_line_projection_comp_projection_gap_px": 320.0,
            "stop_line_projection_comp_max_predictions": 2,
            "stop_line_projection_comp_second_min_fragment_count": 5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "lane_center_offset_field": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 2.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 2.25,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_track_mode": "row_scan_tangent",
            "lane_segfirst_center_offset_aux_weight": 0.50,
            "lane_segfirst_center_offset_enabled": True,
            "lane_segfirst_center_offset_max_shift_px": 4.0,
            "lane_segfirst_center_offset_min_support_score": 0.35,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
            "stop_line_projection_comp_enabled": True,
            "stop_line_projection_comp_min_gap": 4.0,
            "stop_line_projection_comp_topk": 50,
            "stop_line_projection_comp_union_min_score": 0.80,
            "stop_line_projection_comp_single_min_score": 0.90,
            "stop_line_projection_comp_angle_threshold_deg": 16.0,
            "stop_line_projection_comp_offset_threshold_px": 48.0,
            "stop_line_projection_comp_min_cluster_count": 2,
            "stop_line_projection_comp_projection_gap_px": 320.0,
            "stop_line_projection_comp_max_predictions": 2,
            "stop_line_projection_comp_second_min_fragment_count": 5,
            "crosswalk_polygon_mode": "hull",
        },
    },
    "core_centerline_cross_conflict_negative": {
        "freeze_policy": "lane_family_heads_only",
        "trunk_lr": 0.0,
        "head_lr": 1.0e-4,
        "loss_weights": {
            "det": 0.0,
            "tl_attr": 0.0,
            "lane": 2.25,
            "stop_line": 1.75,
            "crosswalk": 1.75,
        },
        "overrides": {
            "lane_segfirst_centerline_target_mode": "core",
            "lane_segfirst_task_conflict_negative_mode": "crosswalk",
            "lane_segfirst_task_conflict_negative_weight": 0.35,
            "lane_segfirst_task_conflict_negative_margin": 0.15,
            "lane_segfirst_loss_weights": {
                "centerline_bce": 2.0,
                "centerline_dice": 2.0,
                "support_bce": 0.15,
                "tangent": 0.35,
                "color": 0.5,
                "type": 0.25,
            },
            "stopline_center_target_mode": "heatmap",
            "stopline_selector_aux_weight": 0.5,
            "stopline_geometry_aux_weight": 1.5,
            "stopline_local_x_aux_weight": 0.5,
        },
    },
}


EXPERIMENTS["cross_stitch_task_routing"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_heads_only",
    "trunk_lr": 0.0,
    "head_lr": 1.0e-4,
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "lane_family_task_adapter_enabled": True,
        "lane_family_cross_stitch_enabled": True,
        "multitask_conflict": {
            "enabled": True,
            "mode": "pcgrad_style",
            "tasks": ["lane", "stop_line", "crosswalk"],
            "param_groups": ["lane_family_adapters"],
        },
    },
}


EXPERIMENTS["stopline_priority_positive_sampler"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "multi:stopline,lane,crosswalk",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["stopline_priority_retention_distill_heads"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_heads_only",
    "trunk_lr": 0.0,
    "head_lr": 1.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 1.50,
        "stop_line": 2.50,
        "crosswalk": 1.50,
    },
    "train_defaults_overrides": {
        "distill_enabled": True,
        "distill_teacher_checkpoint": "__seed_checkpoint__",
        "distill_loss_weights": {
            "lane": 0.35,
            "stop_line": 0.0,
            "crosswalk": 0.35,
        },
        "distill_normalize_mode": "ema",
        "distill_ema_decay": 0.95,
        "distill_ema_warmup_steps": 4,
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "multi:stopline,lane,crosswalk",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["stopline_source_union_projection_comp"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "stopline_selector_target_mode": "rowx_band",
        "stopline_selector_aux_weight": 0.75,
        "stop_line_projection_comp_proposal_source": "center_selector_union",
    },
}

EXPERIMENTS["stopline_cross_priority_lane_frozen"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_stop_cross_heads_only",
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 0.0,
        "stop_line": 2.25,
        "crosswalk": 1.75,
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "multi:stopline,crosswalk",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["stopline_focus_crop_feeding"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "head_lr": 2.0e-4,
    "train_defaults_overrides": {
        "train_augmentation": True,
        "train_augmentation_seed": 260529,
        "train_aug_stopline_focus_crop_prob": 0.75,
        "train_aug_stopline_focus_crop_scale_min": 1.35,
        "train_aug_stopline_focus_crop_scale_max": 1.80,
        "train_aug_stopline_focus_crop_jitter": 0.08,
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "lane_segfirst_center_offset_aux_weight": 0.0,
        "lane_segfirst_center_offset_enabled": False,
    },
}

EXPERIMENTS["stopline_retention_distill_upper_trunk"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_plus_upper_trunk",
    "trunk_lr": 2.0e-6,
    "head_lr": 1.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 1.50,
        "stop_line": 2.50,
        "crosswalk": 1.75,
    },
    "train_defaults_overrides": {
        "distill_enabled": True,
        "distill_teacher_checkpoint": "__seed_checkpoint__",
        "distill_loss_weights": {
            "lane": 0.20,
            "stop_line": 0.0,
            "crosswalk": 0.20,
        },
        "distill_normalize_mode": "ema",
        "distill_ema_decay": 0.95,
        "distill_ema_warmup_steps": 4,
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "multi:stopline,lane,crosswalk",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["task_routed_distill_student"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_heads_only",
    "trunk_lr": 0.0,
    "head_lr": 1.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 1.50,
        "stop_line": 2.50,
        "crosswalk": 1.50,
    },
    "train_defaults_overrides": {
        "distill_enabled": True,
        "distill_teacher_checkpoint": "__seed_checkpoint__",
        "distill_task_teacher_checkpoints": {
            "stop_line": (
                "runs/pv26_exhaustive_od_lane_train/"
                "lane60_stopline_priority_positive_sampler_from_lane60_lane_head_transplant_original_stop_pca_20260512_default_20260529_101745/"
                "phase_4/checkpoints/best.pt"
            ),
        },
        "distill_loss_weights": {
            "lane": 0.15,
            "stop_line": 0.25,
            "crosswalk": 0.15,
        },
        "distill_normalize_mode": "ema",
        "distill_ema_decay": 0.95,
        "distill_ema_warmup_steps": 4,
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "multi:stopline,lane,crosswalk",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["stopline_router_specialist_upper_trunk"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_plus_upper_trunk",
    "trunk_lr": 2.0e-6,
    "head_lr": 2.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 0.0,
        "stop_line": 4.0,
        "crosswalk": 0.0,
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "stopline",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["stopline_v3_isolated_neck"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_stopline_only",
    "trunk_lr": 0.0,
    "head_lr": 2.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 0.0,
        "stop_line": 4.0,
        "crosswalk": 0.0,
    },
    "train_defaults_overrides": {
        "roadmark_architecture": "v3_stopline_isolated",
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "stopline",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["stopline_only_mask_first_specialist"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_stopline_only",
    "trunk_lr": 0.0,
    "head_lr": 2.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 0.0,
        "stop_line": 4.0,
        "crosswalk": 0.0,
    },
    "train_defaults_overrides": {
        "roadmark_architecture": "stopline_only_mask_first",
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "stopline",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["stopline_midpoint_projection_comp"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_stopline_only",
    "trunk_lr": 0.0,
    "head_lr": 2.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 0.0,
        "stop_line": 4.0,
        "crosswalk": 0.0,
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "stopline_midpoint_aux_weight": 1.0,
        "stop_line_projection_comp_proposal_source": "midpoint",
        "task_positive_task": "stopline",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["lane_router_specialist_upper_trunk"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_plus_upper_trunk",
    "trunk_lr": 2.0e-6,
    "head_lr": 2.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 4.0,
        "stop_line": 0.0,
        "crosswalk": 0.0,
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "lane",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["lane_only_segfirst_specialist"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_heads_only",
    "trunk_lr": 0.0,
    "head_lr": 2.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 4.0,
        "stop_line": 0.0,
        "crosswalk": 0.0,
    },
    "train_defaults_overrides": {
        "roadmark_architecture": "lane_only_row_classifier",
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "lane",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["lane_row_native_primary"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "freeze_policy": "lane_family_heads_only",
    "trunk_lr": 0.0,
    "head_lr": 2.0e-4,
    "loss_weights": {
        "det": 0.0,
        "tl_attr": 0.0,
        "lane": 3.0,
        "stop_line": 2.25,
        "crosswalk": 1.75,
    },
    "train_defaults_overrides": {
        "lane_head_mode": "row_native",
    },
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "multi:lane,stopline,crosswalk",
        "task_positive_fraction": 1.0,
    },
}

EXPERIMENTS["cooccur_lane_stop_cross_sampler"] = {
    **EXPERIMENTS["stopline_projection_comp_runtime"],
    "overrides": {
        **EXPERIMENTS["stopline_projection_comp_runtime"]["overrides"],
        "task_positive_task": "cooccur:lane,stopline,crosswalk",
        "task_positive_fraction": 1.0,
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run a short derived phase-4 PV26 lane-family probe from an existing checkpoint. "
            "This is intended to test 60% headroom signals before committing to a multi-day run."
        )
    )
    parser.add_argument("--source-run", required=True, help="Source PV26 meta-train run directory.")
    parser.add_argument("--seed-checkpoint", default="", help="Seed checkpoint. Defaults to <source-run>/phase_4/checkpoints/best.pt.")
    parser.add_argument("--preset", default="default", help="Base PV26 preset.")
    parser.add_argument("--experiment", choices=sorted(EXPERIMENTS), default="upper_trunk_rebalance")
    parser.add_argument("--epochs", type=int, default=3, help="Probe phase-4 epochs.")
    parser.add_argument("--train-batches", type=int, default=512, help="Train batches per probe epoch.")
    parser.add_argument("--val-batches", type=int, default=128, help="Validation batches per probe epoch.")
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--run-root", default="", help="Run root. Defaults to the base scenario run root.")
    parser.add_argument("--preview", action="store_true", help="Enable preview generation for the probe.")
    return parser.parse_args()


def _resolve_seed_checkpoint(source_run: Path, seed_checkpoint: str) -> Path:
    checkpoint = Path(seed_checkpoint).expanduser() if seed_checkpoint else source_run / "phase_4" / "checkpoints" / "best.pt"
    checkpoint = checkpoint.resolve()
    if not checkpoint.is_file():
        raise FileNotFoundError(f"seed checkpoint not found: {checkpoint}")
    return checkpoint


def _lane60_scenario(args: argparse.Namespace, *, source_run: Path, seed_checkpoint: Path) -> tuple[Any, Path, dict[str, Any]]:
    scenario = train_cli.load_meta_train_scenario(args.preset)
    scenario_path = train_cli._default_scenario_path(args.preset)
    phase_index, phase = train_cli._find_phase_by_stage(scenario, stage=STAGE4)
    experiment = dict(EXPERIMENTS[str(args.experiment)])

    phase_overrides = dict(phase.overrides)
    phase_overrides.update(
        {
            "batch_size": int(args.batch_size),
            "device": str(args.device),
            "train_batches": int(args.train_batches),
            "val_batches": int(args.val_batches),
            "trunk_lr": float(experiment["trunk_lr"]),
            "head_lr": float(experiment["head_lr"]),
            "checkpoint_every": 0,
            "task_positive_task": "multi:lane,stopline,crosswalk",
            "task_positive_fraction": 1.0,
            "sampler_ratios": {
                "bdd100k": 0.0,
                "aihub_traffic": 0.0,
                "aihub_lane": 1.0,
                "aihub_obstacle": 0.0,
            },
        }
    )
    phase_overrides.update(dict(experiment.get("overrides", {})))
    probe_phase = replace(
        phase,
        name=f"{phase.name}_{args.experiment}",
        min_epochs=int(args.epochs),
        max_epochs=int(args.epochs),
        patience=int(args.epochs),
        min_delta_abs=0.0,
        loss_weights=dict(experiment["loss_weights"]),
        freeze_policy=str(experiment["freeze_policy"]),
        overrides=phase_overrides,
    )
    phases = list(scenario.phases)
    phases[phase_index - 1] = probe_phase

    train_defaults_replacements = {
        "device": str(args.device),
        "batch_size": int(args.batch_size),
        "train_batches": int(args.train_batches),
        "val_batches": int(args.val_batches),
        "checkpoint_every": 0,
        "profile_device_sync": False,
        "step_history_every_n_steps": 100,
        "step_history_include_grad_details": False,
        "pcgrad_aggregate_every_n_steps": 100,
        "pcgrad_keep_raw_every_n_steps": 1000,
    }
    experiment_train_defaults_overrides = dict(experiment.get("train_defaults_overrides", {}))
    if experiment_train_defaults_overrides.get("distill_teacher_checkpoint") == "__seed_checkpoint__":
        experiment_train_defaults_overrides["distill_teacher_checkpoint"] = str(seed_checkpoint)
    task_teacher_checkpoints = experiment_train_defaults_overrides.get("distill_task_teacher_checkpoints")
    if isinstance(task_teacher_checkpoints, dict):
        experiment_train_defaults_overrides["distill_task_teacher_checkpoints"] = {
            task_name: str(seed_checkpoint) if checkpoint == "__seed_checkpoint__" else checkpoint
            for task_name, checkpoint in task_teacher_checkpoints.items()
        }
    train_defaults_replacements.update(experiment_train_defaults_overrides)
    train_defaults = replace(scenario.train_defaults, **train_defaults_replacements)
    run_root = Path(args.run_root).expanduser().resolve() if args.run_root else scenario.run.run_root
    run_config = replace(
        scenario.run,
        run_root=run_root,
        run_dir=None,
        run_name_prefix=f"lane60_{args.experiment}_from_{source_run.name}",
    )
    preview = replace(scenario.preview, enabled=bool(args.preview), epoch_comparison_grid=bool(args.preview))
    scenario = replace(
        scenario,
        train_defaults=train_defaults,
        run=run_config,
        preview=preview,
        phases=tuple(phases),
    )
    lineage = {
        "mode": "lane60_probe",
        "experiment": str(args.experiment),
        "source_run_dir": str(source_run),
        "seed_checkpoint_path": str(seed_checkpoint),
        "selected_phase_index": int(phase_index),
        "probe_phase": {
            "epochs": int(args.epochs),
            "train_batches": int(args.train_batches),
            "val_batches": int(args.val_batches),
            "freeze_policy": str(probe_phase.freeze_policy),
            "loss_weights": dict(probe_phase.loss_weights),
            "overrides": dict(phase_overrides),
        },
        "train_defaults_overrides": dict(experiment_train_defaults_overrides),
    }
    return scenario, scenario_path, {
        "selected_phase_indices": (phase_index,),
        "initial_best_checkpoint": seed_checkpoint,
        "lineage": lineage,
    }


def main() -> int:
    args = parse_args()
    source_run = Path(args.source_run).expanduser().resolve()
    if not source_run.is_dir():
        raise FileNotFoundError(f"source run not found: {source_run}")
    seed_checkpoint = _resolve_seed_checkpoint(source_run, str(args.seed_checkpoint or ""))
    scenario, scenario_path, options = _lane60_scenario(args, source_run=source_run, seed_checkpoint=seed_checkpoint)
    summary = train_cli.run_meta_train_scenario(
        scenario,
        scenario_path=scenario_path,
        selected_phase_indices=options["selected_phase_indices"],
        initial_best_checkpoint=options["initial_best_checkpoint"],
        lineage=options["lineage"],
    )
    print(json.dumps(train_cli.train_artifacts.json_ready({"summary": summary, "lineage": options["lineage"]}), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
